package com.coinflow.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

@Entity
@Data
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false)
    private String password;

    @Column(nullable = false)
    private String firstName;
    @Column(nullable = false)
    private String lastName;

    @org.hibernate.annotations.CreationTimestamp
    @Column(name = "created_at")
    private LocalDateTime createdAt;

}

// id (Type: Long): The primary key, autogenerated using the identity strategy.

// email (Type: String): This will act as the unique username for login. It
// should be marked as unique at the database level so no two users can register
// with the same email.

// password (Type: String): This will store the password. Crucial security note:
// We will never store plain text here; it will eventually store a secure BCrypt
// hash.

// firstName & lastName (Type: String): Replacing the single ownerName string
// with structured profile fields.

// createdAt (Type: LocalDateTime): A timestamp recording when the user profile
// was registered.